### ISSUE TITLE
One Possible Approach to Fix the Failure of killdockers() Function on Windows System

### ISSUE THREAD

**Issue by ArthasGAO** [enriquetomasmb/fedstellar#14]
I put forward one possible approach (#13) to fix the docker killing bug on Windows system through changing the command dirctly which is not applicable on Windows cmd. I hope you can help review it and make comments accordingly.

**Comment by enriquetomasmb** [comment]
The pull request has been approved and the changes were included in the main branch 35d4595, thanks for your contribution!
