### ISSUE TITLE
slow start learning for ring topo

### ISSUE THREAD

**Issue by luke-feng** [enriquetomasmb/fedstellar#8]
I noticed that if the dfl is not fully or star topo, and the nodes are not directly connected with the start node (by default node 0), then the learning process of this node will start very slow. This is because the start node only broadcast to its neighbors with the start learning msg, for those undirect connected nodes, will receive this msg very late. especially in a sync mode.  Thus I suggest to  add the start learning msg with each node starting their learning, to notify their neighbors to start their learning process.

for example, in node.py 

`    def __start_learning(self, rounds, epochs):

        self.__start_thread_lock.acquire()  # Used to avoid create duplicated training threads
        if self.round is None:
            self.broadcast(
                CommunicationProtocol.build_start_learning_msg(rounds, epochs)
            )`
if its just start to learn, then send the broadcast to its neis to start their learning

**Comment by enriquetomasmb** [comment]
Hi @luke-feng, thank you for your suggestion about the broadcast of the start learning message. A few days ago, I uploaded a new version of Fedstellar using gRPC for communications. It's only a beta version with the same functionality as the main version, probably we could check the performance and then decide its use. Also, it could solve your suggestion.

Link to the branch: [Fedstellar 2.0](https://github.com/enriquetomasmb/fedstellar/tree/fedstellar2.0)
