### ISSUE TITLE
Steps to start

### ISSUE THREAD

**Issue by allent4n** [enriquetomasmb/fedstellar#9]
Can you provide some steps for us to start?

**Comment by enriquetomasmb** [comment]
I recommend you take a look at our papers about DFL and the platform:

https://ieeexplore.ieee.org/document/10251949/ (Preprint: https://arxiv.org/abs/2211.08413)
https://arxiv.org/abs/2306.09750

Regarding the platform's functionality, you have a demo video at http://federatedlearning.inf.um.es about the deployment and monitoring of decentralized federations.

Feel free to ask us any questions or suggestions!
